apiVersion: v1
kind: Service
metadata:
  name: policy-discovery-service
  labels:
    service: policy-discovery-service
spec:
  ports:
  - port: 9089
    targetPort: 9089
    protocol: TCP
  selector:
    container: policy-discovery-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-discovery-service
  labels:
    deployment: policy-discovery-service
spec:
  selector:
    matchLabels:
      container: policy-discovery-service
  template:
    metadata:
      labels:
        container: policy-discovery-service
    spec:
      containers:
      - image: gcr.io/accuknox/snapshot/knoxautopolicy:latest 
        #image: accuknox/knoxautopolicy:latest
        name: policy-discovery-service
        ports:
        - containerPort: 9089
          protocol: TCP
        volumeMounts:
          - mountPath: /conf
            name: config-volume
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: policy-discovery-service-config

