apiVersion: v1
kind: ServiceAccount
metadata:
  name: knoxautopolicy
  namespace: accuknox-autopolicy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knoxautopolicy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: knoxautopolicy
  namespace: accuknox-autopolicy
---
apiVersion: v1
kind: Service
metadata:
  name: knoxautopolicy
  labels:
    service: knoxautopolicy
spec:
  ports:
  - port: 9089
    targetPort: 9089
    protocol: TCP
  selector:
    container: knoxautopolicy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knoxautopolicy
  labels:
    deployment: knoxautopolicy
spec:
  selector:
    matchLabels:
      container: knoxautopolicy
  template:
    metadata:
      labels:
        container: knoxautopolicy
    spec:
      serviceAccountName: knoxautopolicy
      containers:
      - image: accuknox/knoxautopolicy:latest
        name: knoxautopolicy
        ports:
        - containerPort: 9089
          protocol: TCP
        volumeMounts:
          - mountPath: /conf
            name: config-volume
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: knoxautopolicy-config
---
