apiVersion: v1
kind: Namespace
metadata:
  name: knox-auto-policy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knox-auto-policy-daemon
  namespace: knox-auto-policy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knox-auto-policy-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: knox-auto-policy-daemon
  namespace: knox-auto-policy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knox-auto-policy-daemon
  namespace: knox-auto-policy
  labels:
    deployment: knox-auto-policy-daemon
spec:
  selector:
    matchLabels:
      container: knox-auto-policy-daemon
  template:
    metadata:
      labels:
        container: knox-auto-policy-daemon
    spec:
      serviceAccountName: knox-auto-policy-daemon
      containers:
      - image: accuknox/knoxautopolicy:latest
        name: knox-auto-policy-daemon
        env:
        - name: DB_DRIVER
          value: "mongodb"
        - name: DB_PORT
          value: "27017"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "password"
        - name: DB_NAME
          value: "flow_management"
        - name: COL_NETWORK_FLOW
          value: "network_flow"
        - name: COL_DISCOVERED_POLICY
          value: "discovered_policy"
---
