apiVersion: v1 
kind: ConfigMap 
metadata: 
    name: {{ .Values.labels.app }}-config
    #namespace: {{ .Release.Namespace }} 
data:
  conf.yaml: |-
{{ toYaml .Values.config | indent 4 }}
  {{- end }}