version: '3'

services:
  database:
    image: mysql:8.0.17
    ports:
      - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=flow_management
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/

  knoxautopolicy:
    image: image.0x010.com/knox-auto-policy:latest
    restart: unless-stopped
    depends_on:
    - database
    ports:
      - 30520:30520
    environment:
    - NETWORKFLOW_DB_DRIVER=mysql
    - NETWORKFLOW_DB_USER=root
    - NETWORKFLOW_DB_PASS=password
    - NETWORKFLOW_DB_NAME=flow_management
