name: ci-go

on:
  push:
    branches: [master,dev,AK-Dev]
  pull_request:
    branches: [master,dev,AK-Dev]

jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: v1.16

      - name: Check gofmt
        run: gofmt -s -d $(find . -type f -name '*.go' -print)
        working-directory: src

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run Revive Action by pulling pre-built image
        uses: morphy2k/revive-action@v2
        with:
          path: "./src/..."

  go-sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: v1.16

      - name: Run Gosec Security Scanner
        run: |
          go get -u github.com/securego/gosec/v2/cmd/gosec
          go get .
          gosec -exclude=G204,G304,G107 -exclude-dir=protobuf/ ./...  
        working-directory: src

  push-docker-img:
    name: Create auto-policy-discovery img
    if: github.repository == 'accuknox/auto-policy-discovery'
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate artifacts
        run: ./src/build/build_knoxautopolicy.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}
      - name: Push images to Docker
        run: ./src/build/push_knoxautopolicy.sh
