name: ci-test

on:
  push:
    branches: [master,dev]
  pull_request:
    branches: [master,dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: v1.16

      - name: Unit Test
        run: ./tests/test-go-unit.sh